### PR TITLE
Support for NSImage

### PR DESCRIPTION
**Pull request by yageek**
Create two separated frameworks
Add extension to NSImage

To preserve the API, I needed to use kind of new initialisers (declared
in Objective-C). I don’t know if it is the correct way to perform it.

Any suggestion is welcomed

### CODE REVIEW

**Comment by blommegard** [comment]
Think my Github-Fu let me down, but my approach to this is in this PR: https://github.com/madebybowtie/FlagKit/pull/16

**Comment by yageek** [comment]
I was first using something similar as this line to get the asset 
```
 guard let URL = FlagKit.assetBundle.URLForImageResource(countryCode) else {return nil}
```
But it seems to always return nil. As asset are compressed in a `.cab` archive, I'm not sure it is possible to get an URL to it.

**Comment by blommegard** [comment]
For some reason it worked for me here, but maybe I just mixed up with all million of Xcode project I have laying around, will make sure it works for real!

**Comment by yageek** [comment]
Let us know if it succeed this way. 

It would be good to check if the caching is working. I found something here :
http://stackoverflow.com/questions/25091236/whats-the-best-way-to-load-an-image-from-a-framework-in-os-x-yosemite-10-10

**Pull request closed without merging**
