### PR TITLE
Migrate to Swift 5

### PR DESCRIPTION
**Pull request by hannseman**
This PR upgrades to Swift 5 and sets recommended Xcode 10.2 settings.

It would also be nice to get a new release. The reason why I started this PR was that it failed to build on Xcode 10.2 with Carthage since `2.0.1` has `SWIFT_VERSION=3.0`. 

This error will probably hit quite a few users of this library using carthage like this:
`github "madebybowtie/FlagKit" "~> 2.0"`

### CODE REVIEW

**Comment by hannseman** [comment]
Tests seem to fail because of the size of the generated image and the fixture differs. Not really sure how to proceed here. The generated images seem smaller so I guess it have been optimised in the latest SDK. Maybe updating the fixture images is enough?

**Comment by blommegard** [comment]
Thanks, I will have a look at this right away!

**Comment by hannseman** [comment]
@blommegard cool! I've updated the fixtures so the tests should pass now.

**Comment by hannseman** [comment]
Forgot about Apple TV using @1x assets. Updated them as well and now the tests are passing.

**Comment by blommegard** [comment]
Thanks!

I will merge this, do some additional migrations and then try to get a new release out.

**Pull request merged**
