### PR TITLE
#81 Adds SPM Support

### PR DESCRIPTION
**Pull request by matrejek**
This PR adds minimal required stuff as well as moves files in order to provide the ability to use FlagKit with SPM-based projects.

### CODE REVIEW

**Comment by AdrianBinDC** [comment]
@matrejek Very nice! I was just looking through what's new with Swift 5.3 and I saw SPM support for binaries, resources, etc. I was thinking of opening a PR on this, but looks like you beat me to it :)

**Comment by matrejek** [comment]
@AdrianBinDC - thanks for your kind words, I hope that will be merged at some point.

@blommegard @edwardjewson @gellermark - is there any chance to have it reviewed and possibly merged?

**Comment by victormihaita** [comment]
When you think is possible to merge this?

**Comment by matrejek** [comment]
I am using it from my branch in a personal project and it seems fine. Maybe you can try the same? I don't know whether this repo is actively maintained by the owners

**Comment by blommegard** [comment]
Hi and thank you so much @matrejek!

We have had so much to do and this have just not been a priority.
I have looked thru the PR and think it looks good!

**Pull request merged**
